In [2]:
import pandas as pd

## Pandas Series 
- A series is a 1D array. This means it contains a single column

In [7]:
## creating a series data.
student_scores = pd.Series(
    [89,98,79,79,69,56],
    name="student scores",
    index=["Jane","John","James","Joseph","Josephine","Andrew"]
)
student_scores

Jane         89
John         98
James        79
Joseph       79
Josephine    69
Andrew       56
Name: student scores, dtype: int64

In [8]:
student_data={
    "Name":["Jane","John","James","Joseph","Josephine","Andrew"],
    "Science":[89,98,79,79,69,56],
    "Maths":[91,86,95,69,89,66],
    "Gender":["Female","Male","Male","Male","Female","Male"]
}
students=pd.DataFrame(student_data)
students

        Name  Science  Maths  Gender
0       Jane       89     91  Female
1       John       98     86    Male
2      James       79     95    Male
3     Joseph       79     69    Male
4  Josephine       69     89  Female
5     Andrew       56     66    Male

In [9]:
## import Methods
students.shape

(6, 4)

In [10]:
students.head()## first five raws

        Name  Science  Maths  Gender
0       Jane       89     91  Female
1       John       98     86    Male
2      James       79     95    Male
3     Joseph       79     69    Male
4  Josephine       69     89  Female

In [11]:
students.head(4)## show the number specified

     Name  Science  Maths  Gender
0    Jane       89     91  Female
1    John       98     86    Male
2   James       79     95    Male
3  Joseph       79     69    Male

In [12]:
students.tail(2)## bottom value

        Name  Science  Maths  Gender
4  Josephine       69     89  Female
5     Andrew       56     66    Male

In [13]:
students.describe()## summary statistics

         Science      Maths
count   6.000000   6.000000
mean   78.333333  82.666667
std    14.746751  12.143585
min    56.000000  66.000000
25%    71.500000  73.250000
50%    79.000000  87.500000
75%    86.500000  90.500000
max    98.000000  95.000000