In [1]:
import pandas as pd

In [5]:
students=pd.read_csv("StudentsPerformance.csv")
students

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
gaby={
    "Maths":[12,34,56,76,78],
    "Science":[12,43,56,76,45],
    "English":[56,78,98,56,34],
    

}
students=pd.DataFrame(gaby)
students

   Maths  Science  English
0     12       12       56
1     34       43       78
2     56       56       98
3     76       76       56
4     78       45       34

In [7]:
students["Maths"].mean()

np.float64(51.2)

In [9]:
students["Maths"].mode()[0]

np.int64(12)

In [10]:
performance={
    "Students":["John","Marey","Racheal","Gaby"],
    "Maths":[12,45,12,67],
    "English":[23,45,67,45]
    
}
call=pd.DataFrame(performance)
call

  Students  Maths  English
0     John     12       23
1    Marey     45       45
2  Racheal     12       67
3     Gaby     67       45

In [11]:
students.shape

(5, 3)

In [16]:
students.head(7)

   Maths  Science  English
0     12       12       56
1     34       43       78
2     56       56       98
3     76       76       56
4     78       45       34