DataSeries, DataFrames

In [1]:
import pandas as pd

In [2]:
students_data={
    "maths":[80,75,67,90],
    "english":[90,85,70,80],
    "science":[60,65,88,77],
    "french":[60,99,89,73]

}
students=pd.DataFrame(students_data)
students

   maths  english  science  french
0     80       90       60      60
1     75       85       65      99
2     67       70       88      89
3     90       80       77      73

In [3]:
students.shape

(4, 4)

In [4]:
students.head

<bound method NDFrame.head of    maths  english  science  french
0     80       90       60      60
1     75       85       65      99
2     67       70       88      89
3     90       80       77      73>

In [5]:
students.tail

<bound method NDFrame.tail of    maths  english  science  french
0     80       90       60      60
1     75       85       65      99
2     67       70       88      89
3     90       80       77      73>

In [6]:
students.describe

<bound method NDFrame.describe of    maths  english  science  french
0     80       90       60      60
1     75       85       65      99
2     67       70       88      89
3     90       80       77      73>

In [7]:
students.describe()

           maths    english    science    french
count   4.000000   4.000000   4.000000   4.00000
mean   78.000000  81.250000  72.500000  80.25000
std     9.626353   8.539126  12.556539  17.23127
min    67.000000  70.000000  60.000000  60.00000
25%    73.000000  77.500000  63.750000  69.75000
50%    77.500000  82.500000  71.000000  81.00000
75%    82.500000  86.250000  79.750000  91.50000
max    90.000000  90.000000  88.000000  99.00000

In [8]:
students["maths"].mean()

np.float64(78.0)

In [10]:
students["english"].mode()[0]

np.int64(70)

In [11]:
students["science"].median()

np.float64(71.0)

In [12]:
students["maths"].mode()[0]

np.int64(67)

In [13]:
students["maths"].std()

np.float64(9.626352718795768)

In [14]:
students["french"].var()

np.float64(296.9166666666667)

In [15]:
students["french"].max()

np.int64(99)

In [16]:
students["maths"].max()-students["maths"].min()

np.int64(23)

In [19]:
lower_quartile=students["maths"].quantile(0.25)
lower_quartile

np.float64(73.0)

In [20]:
upper_quartile=students["maths"].quantile(0.75)
upper_quartile

np.float64(82.5)

In [21]:
import numpy as np

In [22]:
lower_quartile2=np.percentile(students["english"],90)
lower_quartile2

np.float64(88.5)

In [23]:
lower_quartile2=np.percentile(students["maths"],90)
lower_quartile2

np.float64(87.0)

In [25]:
students=pd.read_csv("StudentsPerformance.csv")
students

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86