STUDENTS MARKS AND DESCRIPTIVE STATISTICS

In [1]:
import pandas as pd


students_marks={
    "science":[89,45,67,89,23,45,67],
    "English":[23,45,87,23,54,67,89],
    "Chemistry":[43,45,76,56,87,34,56],
    "Biology":[43,65,78,98,76,45,65],
    "Names":["Moses","Jane","Aron","Patrick","Gabriel","Olive","james"],
    "Gender":["Male","Female","Male","Male","Male","Female","Male"],
}
students=pd.DataFrame(students_marks)
students

   science  English  Chemistry  Biology    Names  Gender
0       89       23         43       43    Moses    Male
1       45       45         45       65     Jane  Female
2       67       87         76       78     Aron    Male
3       89       23         56       98  Patrick    Male
4       23       54         87       76  Gabriel    Male
5       45       67         34       45    Olive  Female
6       67       89         56       65    james    Male

In [2]:
students.shape

(7, 6)

In [3]:
students.head()

   science  English  Chemistry  Biology    Names  Gender
0       89       23         43       43    Moses    Male
1       45       45         45       65     Jane  Female
2       67       87         76       78     Aron    Male
3       89       23         56       98  Patrick    Male
4       23       54         87       76  Gabriel    Male

In [4]:
students.tail()

   science  English  Chemistry  Biology    Names  Gender
2       67       87         76       78     Aron    Male
3       89       23         56       98  Patrick    Male
4       23       54         87       76  Gabriel    Male
5       45       67         34       45    Olive  Female
6       67       89         56       65    james    Male

In [5]:
students.describe

<bound method NDFrame.describe of    science  English  Chemistry  Biology    Names  Gender
0       89       23         43       43    Moses    Male
1       45       45         45       65     Jane  Female
2       67       87         76       78     Aron    Male
3       89       23         56       98  Patrick    Male
4       23       54         87       76  Gabriel    Male
5       45       67         34       45    Olive  Female
6       67       89         56       65    james    Male>